name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: GitHub Action for SwiftLint with PR Commenting
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --path Sources
          
  build-and-test:
    runs-on: macos-latest
    needs: swiftlint
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Build Package
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
