name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  swiftlint:
    name: SwiftLint
    # use Linux for the SwiftLint action since this GH library requires it (so bot can post inline to PR) 
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4
      
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          WORKING_DIRECTORY: Source
          
  build-and-test:
    runs-on: macos-latest
    needs: swiftlint
    steps:
    - uses: actions/checkout@v4
    
    - name: Generate Xcode Project
      run: swift package generate-xcodeproj
    
    - name: Build for iOS
      run: xcodebuild -project DualCameraKit.xcodeproj -scheme DualCameraKit -destination "platform=iOS Simulator,name=iPhone 14" build
    
    - name: Test
      run: xcodebuild -project DualCameraKit.xcodeproj -scheme DualCameraKit -destination "platform=iOS Simulator,name=iPhone 14" test
