name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  swiftlint:
    name: SwiftLint
    # use Linux for the SwiftLint action since this GH library requires it (so bot can post inline to PR) 
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4
      
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          WORKING_DIRECTORY: Source
          
  build-and-test:
    runs-on: macos-latest
    needs: swiftlint
    steps:
    - uses: actions/checkout@v4
    
    - name: Build for iOS simulator
      run: |
        # Force the use of the iOS simulator SDK
        export SDKROOT=$(xcrun --sdk iphonesimulator --show-sdk-path)
        export DEVELOPER_DIR=$(xcode-select -p)
        export PLATFORM_DIR=$DEVELOPER_DIR/Platforms/iPhoneSimulator.platform
        
        # Build with explicit flags for both Swift and C/ObjC compilation
        swift build \
          -Xswiftc "-sdk" \
          -Xswiftc "$SDKROOT" \
          -Xswiftc "-target" \
          -Xswiftc "x86_64-apple-ios17.0-simulator" \
          -Xcc "-isysroot" \
          -Xcc "$SDKROOT" \
          -Xcc "-target" \
          -Xcc "x86_64-apple-ios17.0-simulator" \
          -Xcc "-F$PLATFORM_DIR/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks"
        
    - name: Run tests
      run: |
        swift test \
          -Xswiftc "-sdk" \
          -Xswiftc "$(xcrun --sdk iphonesimulator --show-sdk-path)" \
          -Xswiftc "-target" \
          -Xswiftc "x86_64-apple-ios15.0-simulator"
