name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install SwiftLint
        run: brew install swiftlint
        
      - name: Run SwiftLint
        run: |
          TMPFILE=$(mktemp)
          swiftlint --reporter json --path Sources > $TMPFILE || true
          
          # Process SwiftLint output and create GitHub annotations
          jq -r '.[] | "::warning file=\(.file),line=\(.line),col=\(.character)::\(.reason)"' $TMPFILE || true
  
  build-and-test:
    runs-on: macos-latest
    needs: swiftlint
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Package
      run: xcodebuild -resolvePackageDependencies -scheme DualCameraKit -destination "platform=iOS Simulator,name=iPhone 16,OS=18.0" -sdk iphonesimulator
    - name: Run tests
      run: swift test -v
